In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/rcsb_pdb_custom_report_20260414150250.csv', header=0)

In [ ]:
df.shape

(413, 5)

In [ ]:

df.columns = df.iloc[0]

In [ ]:

df.dropna(how='all', axis=1, inplace=True)

In [ ]:
df.shape

(413, 4)

In [ ]:
df.head()

,Entry ID,Sequence,Auth Asym ID,Entity ID
0,Entry ID,Sequence,Auth Asym ID,Entity ID
1,1AAL,RPDFCLEPPYTGPCKARIIRYFYNAKAGLVQTFVYGGCRAKRNNFK...,B,1
2,NaN,NaN,A,NaN
3,1AAP,VREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFD...,B,1
4,NaN,NaN,A,NaN

In [ ]:
df = df.dropna()

In [ ]:
df.shape

(136, 4)

In [ ]:
df = df[df["Sequence"].str.len().between(40, 80)]

In [ ]:
df.head()

,Entry ID,Sequence,Auth Asym ID,Entity ID
0,1AAL,RPDFCLEPPYTGPCKARIIRYFYNAKAGLVQTFVYGGCRAKRNNFK...,B,1
2,1AAP,VREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFD...,B,1
4,1B0C,RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFK...,E,1
9,1BHC,RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFK...,A,1
19,1BPI,RPDFCLEPPYTGPCKARIIRYFYNAKAGLCQTFVYGGCRAKRNNFK...,A,1

In [ ]:
df.shape

(106, 4)

In [ ]:
df.to_csv('protein.csv', index=False)

In [ ]:
id = []
with open ("/content/mmseqs2_8348530.out", "r") as f:
  for line in f:
    line = line.strip()
    if line[0] == ">":
      id.append(line[1:])

In [ ]:
print(id)

['1AAP', '1D0D', '1KNT', '1TFX', '1YC0', '1ZR0', '3FP7', '3L33', '3P92', '3TGI', '4DTG', '4ISO', '4U30', '5JB6']

In [ ]:
df_filtrato = df[df[df.columns[0]].isin(id)]

In [ ]:
df_filtrato.head()

,Entry ID,Sequence,Auth Asym ID,Entity ID
3,1AAP,VREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNNFD...,B,1
54,1D0D,YNRLCIKPRDWIDECDSNEGGERAYFRNGKGGCDSFWICPEDHTGA...,A,1
79,1KNT,ETDICKLPKDEGTCRDFILKWYYDPNTKSCARFWYGGCGGNENKFG...,A,1
135,1TFX,KPDFCFLEEDPGICRGYITRYFYNNQTKQCERFKYGGCLGNMNNFE...,C,2
141,1YC0,MKHQHQHQHQHQHQMHQTEDYCLASNKVGRCRGSFPRWYYDPTEQI...,I,2

In [ ]:
df_filtrato.size

56

In [ ]:
with open("PDB_code.txt", "w") as f:
    for riga in df_filtrato.itertuples(index=False):
        linea = f"{riga[0]}:{riga[2]}\n"
        f.write(linea)